---

- name: IOS-XE - WAN MACsec EAPoL Modification Playbook
  hosts: routers
  connection: local
  gather_facts: no
  #  I decided to enter MPLS VPN variables directly into the Playbook.  There are other options of course
  
  vars:
    int_name: TenGigabitEthernet0/0/0
    e_type_num: 876F
    eapol_address: broadcast-address

  tasks:
  - name: Get Login credentials
    include_vars: ~/access.yml

  - name: Define Provider
    set_fact:
      provider:
      #  This references my "access.yml' file for login credentials
        host: "{{ inventory_hostname }}"
        # host: "{{ device_ip }}"
        username: "{{ access['username'] }}"
        password: "{{ access['password'] }}"

#  I used variables for all of the needed commands, offering flexibility for the operator

  - name: Apply MACsec EAPoL Options to Interface
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - eapol eth-type {{ e_type_num }}
        - eapol destination-address {{ eapol_address }}
      parents: ['interface {{ int_name }}']
      match: exact

  handlers:
   - name: write config
     ios_config:
        provider: "{{ provider }}"
        save_when: modified

...