---

- name: IOS-XE - WAN MACsec - MKA Interface Change Playbook
  hosts: routers
  connection: local
  gather_facts: no
  #  I decided to enter MPLS VPN variables directly into the Playbook.  There are other options of course
  
  #vars:
  #  chain_name: key-roll-16
    

  tasks:
  - name: Get Login credentials
    include_vars: ~/access.yml

  - name: Define Provider
    set_fact:
      provider:
      #  This references my "access.yml' file for login credentials
        host: "{{ inventory_hostname }}"
        username: "{{ access['username'] }}"
        password: "{{ access['password'] }}"

#  I used variables for all of the needed commands, offering flexibility for the operator

  - name: Apply MKA Key Chain to Config
    ios_config:
      provider: "{{ provider }}"
      src:  key_chain_template.j2
      match: line

  handlers:
   - name: write config
     ios_config:
        provider: "{{ provider }}"
        save_when: modified

...