---

- name: IOS-XE - WAN MACsec - MKA Interface Change Playbook
  hosts: routers
  connection: local
  gather_facts: no
  #  I decided to enter MPLS VPN variables directly into the Playbook.  There are other options of course
  
  vars:
    int_ten_name: TenGigabitEthernet0/0/0
    int_gig_name: GigabitEthernet0/0/5
    policy_name: key-roll-18
    
  tasks:
  - name: Get Login credentials
    include_vars: ~/access.yml

  - name: Define Provider
    set_fact:
      provider:
      #  This references my "access.yml' file for login credentials
        host: "{{ inventory_hostname }}"
        username: "{{ access['username'] }}"
        password: "{{ access['password'] }}"

#  I used variables for all of the needed commands, offering flexibility for the operator

  - name: Apply MKA POLICY to 10 Gig Interface
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - mka pre-shared-key key-chain {{ policy_name }}
      parents: ['interface {{ int_ten_name }}']
      match: exact

  - name: Apply MKA POLICY to 1 Gig Interface
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        - mka pre-shared-key key-chain {{ policy_name }}
      parents: ['interface {{ int_gig_name }}']
      match: exact

  handlers:
   - name: write config
     ios_config:
        provider: "{{ provider }}"
        save_when: modified

...